language: ruby
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
before_script:
  - "cp config/database.yml.sample config/database.yml"
  - "bundle exec rake db:test:prepare db:migrate"
