language: ruby
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-19mode

bundler_args: "--without development production"

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:test:prepare"
